### ISSUE TITLE
HOW to train it from scratch and dataset link?

### ISSUE THREAD

**Issue by Crescentz** [hasanabs/B_DNN#3]
HOW to train it from scratch and dataset link?

**Comment by hasanabs** [comment]
The dataset is generated and trained from the B-DNN_Training.py file, so we don't need to train it from scratch or use an external dataset since the structure of the B-DNN_Training.py and the B-DNN_Prediction.py are the same.

But if you want to train it from scratch, you can generate the training data from B-DNN_Training.p and save it in a table file (using Numpy, Pandas, etc.). Next, you can load the saved training dataset and train your network separately.
